#!/bin/sh

ram=$(free -h | awk '/Mem/ {print $3}')
echo "🐏 "$ram""

case $BLOCK_BUTTON in
    1) "$TERMINAL" -e htop;;
    3) notify-send -t 8000 "$(ps axch -o cmd:10,%mem --sort=-%mem | sed 's/$/%/g' | head)" ;;
esac
