#!/bin/sh

openprice=$(curl -s https://query1.finance.yahoo.com/v7/finance/quote?symbols=amd | sed 's/:/\n/g' | grep "averageDailyVolume3Month" | cut -d ',' -f1)
currentprice=$(curl -s https://query1.finance.yahoo.com/v7/finance/quote?symbols=amd | sed 's/:/\n/g' | grep "bidSize" | cut -d ',' -f1)

if [ "$openprice" -gt "$currentprice" ]; then
    echo "💲AMD ⬇️"$currentprice""
else
    echo "💲AMD ⬆️"$currentprice""
fi

case $BLOCK_BUTTON in
    1) "$TERMINAL" -e mop ;;
esac

