#!/bin/sh

#test for internet
#{ [ $(ping 1.1.1.1 > /dev/null 2>&1) ] && echo "internet is up" ;} || echo "internet is down"


CYAN='\033[0;36m'
GREEN='\033[0;32m'
NC='\033[0m'

#[ -d "~/.config/dunst" ] && echo "That shit exist"



#[ -e ~/.config/dunst ] && echo "yes it exists"
#[ -e ~/.config/wownice ] || echo "no it doesn't exist"

if { [ -e artist ] && [ -e artist/album ]; }; then
    echo "they both exist"
elif { [ -e artist ] && [ ! -e artist/album ]; }; then
    echo "artist exists but album doesn't"
else
    echo "they do not exist"
fi

#! command -v mutter > /dev/null && echo "mutter is not installed"

while IFS=: read -r line; do

    if ! [ -x "$(command -v "$line")" ]; then
        #sudo pacman --noconfirm -S "$line"
        echo -e "${CYAN}"$line" is not installed, installing now${NC}"
    else
        echo -e "${GREEN}"$line" is already installed${NC}"
    fi

done < fordeletetest

#set variables for browser, editor, and terminal
#actually I don't think this is necessary, but I will
#leave it just in case
#[ -z "$EDITOR" ] && export EDITOR="nvim"
#[ -z "$BROWSER" ] && export EDITOR="firefox"
#[ -z "$TERMINAL" ] && export EDITOR="urxvt"
