#!/usr/bin/env python
from bs4 import BeautifulSoup
import requests
import webbrowser
import sys

location = "/tmp/"

req = requests.get("https://teddit.namazso.eu/r/wallpapers")
firefox = webbrowser.Mozilla("/usr/bin/firefox")
soup = BeautifulSoup(req.content, "html.parser")

total = 0
thumbs = []

def findPics(html, holder):
    global total
    for i in html.find_all('img'):
        i['src'] = i['src'].replace("/thumbs/thumb_w:108", "/w:null")
        if total == 0:
            total += 1
            continue
        if i['src'] not in holder:
            total +=1 
            holder.append(i['src'])

def getPics(pics, amount=5):
    get = total - amount - 1
    for i in range(len(pics) - get):
        url = f"https://teddit.net{thumbs[i]}"
        filename = url.split('_')[1]
        r = requests.get(url)
        with open(f"{location}{filename}", "wb") as f:
            f.write(r.content)
        print(f"{filename} Done")

findPics(soup, thumbs)
try:
    getPics(thumbs, int(sys.argv[1]))
except IndexError:
    getPics(thumbs)
