#!/bin/sh

read -p "what would you like the artist directory to be called? " artistname
read -p "what would you like the album directory to be called? " albumname

if { [ -n ~/music/$artistname ] && [ -n ~/music/$artistname/$albumname ]; }; then
    echo "That already exists"
elif { [ -n ~/music/$artistname ] && [ ! -n ~/music/$artistname/$albumname ]; }; then 
    mkdir ~/music/$artistname/$albumname
    cd ~/music/$artistname/$albumname
    musicpath=$PWD
    youtube-dl -f m4a $1
    [ ! -n ~/downloadmusic ] && mkdir ~/downloadmusic
    cd ~/downloadmusic
    mv * album
    mv album "$musicpath"
    cd "$musicpath"
    touch times
else
    mkdir ~/music/$artistname
    mkdir ~/music/$artistname/$albumname
    cd ~/music/$artistname/$albumname
    musicpath=$PWD
    youtube-dl -f m4a $1
    [ ! -n ~/downloadmusic ] && mkdir ~/downloadmusic
    cd ~/downloadmusic
    mv * album
    mv album "$musicpath"
    cd "$musicpath"
    touch times
fi
