#!/bin/sh
#give url of picture or colon seperated list, url;name
[ -z "$1" ] && notify-send "Please enter a url or list" && exit

if [ "$(echo "$1" | grep "http")" ]; then 
    echo "What do you want the file to be called? "; read -r filename
    wget -O "$filename" "$1"
    mv "$filename" "$HOME"/walls
else
    while IFS= read -r line; do
        url=$(echo "$line" | cut -d ';' -f1)
        echo "$url"
        name=$(echo "$line" | cut -d ';' -f2)
        echo "$name"
        wget -O "$name" "$url"
        mv "$name" "$HOME"/walls
    done < "$1"
fi

