#!/bin/sh
#give url of picture or colon seperated list, url;name

if [ $(echo "$1" | grep "http") ]; then 
    echo "What do you want the file to be called? "; read -r filename
    wget -O "$filename" "$1"
    mv "$filename" ~/walls
else
    while IFS= read -r line; do
        url=$(echo "$line" | cut -d ';' -f1)
        echo "$url"
        name=$(echo "$line" | cut -d ';' -f2)
        echo "$name"
        wget -O "$name" "$url"
        mv "$name" ~/walls
    done < "$1"
fi

