#!/bin/sh

movieurl="https://torrentgalaxy.to/torrents.php?search="
animeurl="https://nyaa.si/?f=0&c=0_0&q="

menu() {
    clear
    echo -e "\t1. Watch Anime"
    echo -e "\t2. Watch Movie"
    echo -e "\t3. Exit"
    echo -en "\t\tEnter Option: "
    read -n1 useranswer
}

while :; do
    menu
    echo ""
    case $useranswer in
        1) read -p "Enter the anime to find: " useranime
            url="$animeurl${useranime// /_}"
            nohup firefox $righturl >/dev/null 2>&1 & ;;
        2) read -p "Enter the movie to find: " usermovie
            url="$movieurl${usermovie// /+}#results"
            nohup firefox $url >/dev/null 2>&1 & ;;
        3) break ;;
        *) echo "Wrong Selection" ;;
    esac
    echo ""    
    echo -en "\n\n\t\tEnter anything to continue"
    read -n 1 response
done



