#!/bin/sh

movieurl="https://torrentgalaxy.to/torrents.php?search="
animeurl="https://nyaa.si/?f=0&c=0_0&q="

menu() {
    clear
    printf "\t1. Watch Anime\n"
    printf "\t2. Watch Movie\n"
    printf "\t3. Exit\n"
    printf "\t\tEnter Option: "
    read -r useranswer
}

while :; do
    menu
    echo ""
    case $useranswer in
        1) printf "Enter the anime to find: "; read -r useranime
            url="$animeurl${useranime// /_}"
            nohup firefox $url >/dev/null 2>&1 & ;;
        2) printf "Enter the movie to find: "; read -r usermovie
            url="$movieurl${usermovie// /+}#results"
            nohup firefox $url >/dev/null 2>&1 & ;;
        3) break ;;
        *) printf "\tWrong Selection" ;;
    esac
    echo ""    
    printf "\n\n\t\tEnter anything to continue"
    read -r response
done



