#!/bin/sh
#TODO
#add detailed output
#ask user where to store file??? or just make a temporary location that you delete afterwards idk


counter=1
while read line; do
    end="$(echo "$line" | cut -d' ' -f1)"
    tracknum=$(($counter - 1))

    echo "This is loop number $counter"
    if [[ -n $start ]]; then
        echo $filename
        echo "Track $tracknum is called $name and starts at $start and ends at $end"
        ffmpeg -nostdin -i $1 -ss $start -to $end -c copy $filename
    else
        echo "start doens't exist"
    fi

    start="$end"
    echo "loop $counter has ended"
    echo 
    name=`echo $line | cut -c 10-`
    fakename=`echo $name | sed 's/\s/_/g'`
    filename="$fakename"".m4a"
    counter=$(($counter + 1))


done < $2

echo $start
echo $end
ffmpeg -nostdin -i $1 -ss $start -c copy $filename

