#!/bin/sh
#TODO add program list to fordeletetest

###
#requires a list of programs to be installed
###

#make sure you have networkmanager, networkmanager-runit, 
#opensshand git installed already
#make sure you have generated your ssh keys and added them on github

CYAN='\033[0;36m'
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'

#check for internet connection
if ping -q -c 1 -W 1 1.1.1.1 > /dev/null 2>&1; then
    echo "${GREEN}Internet is up${NC}"
else
    echo "${RED}$Internet is down${NC}"
    exit
fi

#check if programs are installed, install them if not
while IFS=: read -r line; do

    if ! [ -x "$(command -v "$line")" ]; then
        echo -e "${CYAN}"$line" is not installed, installing now${NC}"
        sudo pacman --noconfirm -S "$line"
    else
        echo -e "${GREEN}"$line" is already installed${NC}"
    fi

done < fordeletetest

#check if directories exist and create them if they don't
[ ! -e ~/.config/dunst ] && mkdir ~/.config/dunst
[ ! -e ~/.config/alacritty ] && mkdir ~/.config/alacritty
[ ! -e ~/.config/ncmpcpp ] && mkdir ~/.config/ncmpcpp
[ ! -e ~/.config/nvim ] && mkdir ~/.config/nvim
[ ! -e ~/.config/picom ] && mkdir ~/.config/picom
[ ! -e ~/.config/ranger ] && mkdir ~/.config/ranger
[ ! -e ~/.i3 ] && mkdir ~/.i3
[ ! -e ~/.mpd ] && mkdir ~/.mpd
[ ! -e ~/music ] && mkdir ~/music
[ ! -e ~/walls ] && mkdir ~/walls
[ ! -e ~/scripts ] && mkdir ~/scripts
[ ! -e ~/newsboat ] && mkdir ~/newsboat

#cp configs from git directory
/bin/cp -rf ~/archconfig/dunstrc ~/.config/dunst/
/bin/cp -rf ~/archconfig/ncmpcppbindings ~/.config/ncmpcpp/bindings
/bin/cp -rf ~/archconfig/init.vim ~/.config/nvim/
/bin/cp -rf ~/archconfig/picom.conf ~/.config/picom/
/bin/cp -rf ~/archconfig/rc.conf ~/.config/ranger/
/bin/cp -rf ~/archconfig/rifle.conf ~/.config/ranger/
/bin/cp -rf ~/archconfig/alacritty.yml ~/.config/alacritty/
/bin/cp -rf ~/archconfig/mpd.conf ~/.mpd/
/bin/cp -rf ~/archconfig/config ~/.i3/
/bin/cp -rf ~/archconfig/i3scripts/* ~/.i3/scripts
/bin/cp -rf ~/archconfig/walls/* ~/walls
/bin/cp -rf ~/archconfig/systemscripts/* ~/scripts/
/bin/cp -rf ~/archconfig/.newsboat/* ~/.newsboat/
/bin/cp -rf ~/archconfig/.Xdefaults ~/
/bin/cp -rf ~/archconfig/.xinitrc ~/
/bin/cp -rf ~/archconfig/.zprofile ~/
/bin/cp -rf ~/archconfig/.zshrc ~/


