#!/bin/sh


selection=$(printf "MouseReview
LivestreamFail
Cyberpunk
privacytoolsIO
destiny
linux
linuxmasterrace
linuxquestions
archlinux
artixlinux
voidlinux" | dmenu -fn "Liberation Mono-13" -i -l 10)

url=""https://teddit.net/r/""$selection""

[ -z "$selection" ] && notify-send "Nothing selected..." && exit

if [ "$(pgrep firefox)" ]; then
    firefox "$url" &
else
    qutebrowser "$url" &
fi

notify-send "Opening "$selection""
