#!/bin/sh

thetext=$(printf "<a href="pics/title1" target"_blank">
            <img src="pics/thumbs/title2">
            </a>")

while IFS= read -r line; do
    realname=$(echo "$line" | cut -d ';' -f1)
    thumbname=$(echo "$line" | cut -d ';' -f2)
    echo "$thetext" | sed "s/title1/$realname/;s/title2/$thumbname/" >> correctedforwebsite.txt

done < namesofpics
