#!/bin/sh

while IFS= read -r line; do
    title=$(printf "$line" | sed 's/^/thumbnail-/')
    #ffmpeg requires the -nostdin flag when used in loop
    ffmpeg -nostdin -i "$line" -vf scale=192:108 "$title"
done < paps
