#!/bin/sh

streamerfunc() {
    streamer=$(printf "xQc\nTrihex\nDestiny\nElajjaz\nLilyPichu\nHasanabi\nWillNeff" | dmenu -fn "Liberation Mono-13" -i -l 10)
    notify-send "Opening "$streamer"'s Stream..."
    mpv "https://www.twitch.tv/"$streamer""
    [ $? -eq 2 ] && notify-send ""$streamer" is offline ☹️" && exit 1
}

streamerfunc
