#!/bin/sh
#
[ ! -d "/usr/share/doc/arch-wiki" ] && notify-send "arch-wiki-docs package needed..." && exit 1
selection=$(ls /usr/share/doc/arch-wiki/html/en | sed 's/\.html//g' | dmenu -fn "Liberation Mono-13" -i -l 20)
firefox "/usr/share/doc/arch-wiki/html/en/"$selection".html"
