#!/bin/sh

userquery="$(echo "" | dmenu -fn "Liberation Mono-13" -p "Search: ")"
[ -z "$userquery" ] && notify-send "Nothing selected... exiting" && exit 
searchurl="https://en.wikipedia.org/w/index.php?search=$userquery&title=Special%3ASearch&profile=default&fulltext=1&ns0=1"

curl -s "$searchurl" > /tmp/wikisearchurl

#get article names
{ grep -io '<a href="/wiki/[a-zA-Z0-9_()-]\+' | cut -d'/' -f3; } < /tmp/wikisearchurl > /tmp/wikinames


chosen="$( dmenu -fn "Liberation Mono-13" -l 10 -p "Choose one: " < /tmp/wikinames)"
echo "$chosen"

firefox "https://en.wikipedia.org/wiki/$chosen"

#extract article titles to give to dmenu for user selection





