#!/bin/sh
#take the last 4 lines and
#make file called namesofpics

#need file1 to be list of normal names
#need file2 to be list of thumbnail names


#what it is supposed to look like
# <a href="pics/lain.jpeg" target="_blank">
#     <img src="pics/thumbs/thumbnail-lain.jpeg">
# </a>

thetext=$(printf "<a href="pics/title1" target"_blank">
            <img src="pics/thumbs/title2">
            </a>")

while IFS= read -r line; do
    realname=$(echo "$line" | cut -d ';' -f1)
    thumbname=$(echo "$line" | cut -d ';' -f2)
    echo "The real name of the file is "$realname""
    echo "The thumbnail name is "$thumbname""

done < namesofpics

nicepic1.jpeg;thumbnail-nicepic1.jpeg
coolbird3.png;thumbnail-coolbird3.png
bluefountain.png;thumbnail-bluefountain.png
coolbird8.png;thumbnail-coolbird8.png
