#!/usr/bin/perl
use utf8;
use warnings;

print "Enter the radius of the circle: ";
$radius = <STDIN>;
$pi = 3.14159;
$circumference = (2 * $pi) * $radius;
if ( $radius < 0 ) {
    print "The circumference is 0.\n";
} else {
    print "The circumference of the circle is $circumference.\n";
}


chomp ($num1 = <STDIN>);
chomp ($num2 = <STDIN>);
$product = ($num1 * $num2);
print "The product of $num1 and $num2 is $product\n";

#on last problem

print "Enter a word: ";
$userword = <STDIN>;
print "Enter a number: ";
chomp ($usernumber = <STDIN>);
print $userword x $usernumber;

