#!/usr/bin/perl
use utf8;

# foreach $i (reverse("dicks", "boobs", "butts")) {
#     print "$i\n";
# }


# $counter=0;
# foreach $i (reverse((@meme=<STDIN>))) {
#     $counter+=1;
#     print "$counter $i\n";
# }

# print "Enter some lines, and then press Ctrl-d\n";
# print reverse<STDIN>;

@names = qw/ fred betty barney dino wilma pebbles bamm-bamm /;


foreach $i (1, 2, 3, 1) {
    print "@names[$i - 1]\n";
}
